apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-FS106
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fs106
  template:
    metadata:
      labels:
        app: fs106
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        securityContext:
          privileged: true
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]