apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: frontend
spec:
  containers:
  - image: nginx
    name: web-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: web-sa
status: {}
