apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: web-role
  namespace: frontend
rules:
- apiGroups:
  - ""
  resourceNames:
  - web-pod
  resources:
  - pods
  - endpoints
  verbs:
  - get
  - list
  - watch