apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: devops
  name: devops
  namespace: fastcampus
spec:
  containers:
  - image: nginx
    name: devops
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
